In [2]:
import numpy as np

In [12]:
m=np.random.rand(3,3)
m

array([[0.62567847, 0.46326994, 0.00726676],
       [0.8155142 , 0.38556281, 0.61161552],
       [0.68113516, 0.88638694, 0.77916693]])

In [8]:
m1=np.random.rand(100,100)

In [10]:
m1

array([[0.05031633, 0.23784078, 0.12767115, ..., 0.26215532, 0.09126548,
        0.17369096],
       [0.12398106, 0.45968798, 0.98669258, ..., 0.97491639, 0.63091391,
        0.16993197],
       [0.7278733 , 0.68804636, 0.56080094, ..., 0.59835261, 0.48580101,
        0.22637435],
       ...,
       [0.99850247, 0.9743812 , 0.55403014, ..., 0.25891422, 0.9625849 ,
        0.72170513],
       [0.27697171, 0.10721158, 0.33033357, ..., 0.42028431, 0.77957718,
        0.57385975],
       [0.63305588, 0.73953717, 0.55455449, ..., 0.59126352, 0.9461325 ,
        0.09924105]])

In [18]:
m1[50][50]

np.float64(0.13847452466895793)

In [21]:
m2=np.arange(10,50)
m2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [24]:
m2[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [27]:
m3=np.arange(0,9).reshape(3,3)
m3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
m5=np.ones((10,10))
m5[1:-1,1:-1]=0
m5

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
import random

In [62]:
m6=np.zeros((8,8))
x = np.random.randint(1,99,(6,6))
m6[1:-1,1:-1] = x

m6

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 21., 18., 22., 90., 85., 94.,  0.],
       [ 0., 89.,  6., 20., 94., 94., 37.,  0.],
       [ 0., 88., 64., 94., 94., 14., 10.,  0.],
       [ 0., 88., 86.,  2., 74., 50., 13.,  0.],
       [ 0., 53., 47., 30., 60., 20., 66.,  0.],
       [ 0., 71., 35., 17., 11., 35.,  9.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [108]:
# Media, Mediana y Moda
arr=np.random.rand(1000000)
mean=np.mean(arr)
std_dev=np.std(arr)

In [69]:
mean

np.float64(0.4998794606296067)

In [71]:
std_dev

np.float64(0.28856321820295877)

In [73]:
arr

array([0.85199366, 0.7461205 , 0.3654699 , ..., 0.05119557, 0.71021644,
       0.98150267])

In [83]:
arr=np.arange(10)
np.save('archivo1',arr)

In [80]:
m7=np.load('archivo.npy')

In [84]:
m7[40000]

np.float64(0.22237994963817076)

In [88]:
m8=np.load('archivo1.npy')
m8[9]

np.int64(9)

In [118]:
np.savetxt('archivo.csv',arr,delimiter=',')

In [120]:
m9=np.loadtxt('archivo.csv',delimiter=',')
m9

array([[5.0e+00, 8.0e+17],
       [5.0e+00, 8.0e+17],
       [5.0e+00, 8.0e+17],
       ...,
       [8.0e+00, 4.9e+18],
       [3.0e+00, 2.1e+18],
       [3.0e+00, 8.5e+18]])

In [121]:
m9[29]

array([5.e+00, 8.e+17])